# Generated by Django 4.1.7 on 2023-02-28 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipes_pub_date_alter_recipes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorits', to='recipes.recipes'),
        ),
    ]
